#!/bin/sh

__dirname="$(dirname "$(realpath "$0")")"
. "${__dirname}/context"

sudo -v

mkdir -p "${builds}"
cd "${builds}"

sudo rm -rf "${base}"

template="Package: ${name}
Description: ${description}
Version: ${version}
Maintainer: ${maintainer}
Architecture: ${arch}
Section: base
Priority: optional"

mkdir -p "${base}/DEBIAN"
echo "${template}" > "${base}/DEBIAN/control"

mkdir -p "${base}${bin}"
unzip "${downloads}/${zipfile}" -d "${base}${bin}/${name}"
sudo chown -R "root:root" "${base}"

cd "${cwd}"
