#!/bin/sh

__dirname="$(dirname "$(realpath "$0")")"
. "${__dirname}/context"

mkdir -p "${downloads}"
cd "${downloads}"

# download compressed binary, checksum, and signature
if ! test -e "${zipfile}"
then
  echo "downloading ${zipfile}"
  curl -O "https://${host}/${name}/${version}/${zipfile}"
fi

if ! test -e "${sumfile}"
then
  echo "downloading ${sumfile}"
  curl -O "https://${host}/${name}/${version}/${sumfile}"
fi

if ! test -e "${sigfile}"
then
  echo "downloading ${sigfile}"
  curl -O "https://${host}/${name}/${version}/${sigfile}"
fi

# verify checksum with signature
echo "verifying ${sumfile} with ${sigfile}"
gpg --verify "${sigfile}" "${sumfile}"
if test "$?" != "0"
then
  echo "${name} signature doesn't match key"
  exit 1
fi

# verify compressed binary with checksum
cat "${sumfile}" | grep "${zipfile}" | shasum -a "${sha}" -c -
if test "$?" != "0"
then
  echo "${name} binary doesn't match sha${sha}sum"
  exit 1
fi

cd "${cwd}"
